export enum TypeKeys {
    INITIALIZE_APP_REQUESTED = 'INITIALIZE_APP_REQUESTED',
    INITIALIZE_APP_COMPLETED = 'INITIALIZE_APP_COMPLETED',
    INITIALIZE_APP_FAILED = 'INITIALIZE_APP_FAILED',
    APP_CONFIG_RECEIVED = 'APP_CONFIG_RECEIVED',
    INITIALIZE_MODEL_COMPLETED = 'INITIALIZE_MODEL_COMPLETED',
    SET_RESULT = 'SET_RESULT'
}
