export enum TypeKeys {
    INITIALIZE_APP_REQUESTED = 'INITIALIZE_APP_REQUESTED',
    INITIALIZE_APP_COMPLETED = 'INITIALIZE_APP_COMPLETED',
    INITIALIZE_APP_FAILED = 'INITIALIZE_APP_FAILED',
    CONFIG_CHUNK_RECEIVED = 'CONFIG_CHUNK_RECEIVED',
    INIT_CONFIG_CHECKED = 'INIT_CONFIG_CHECKED'
}
