export enum TypeKeys {
    INITIALIZE_APP_REQUESTED = 'INITIALIZE_APP_REQUESTED',
    INITIALIZE_APP_COMPLETED = 'INITIALIZE_APP_COMPLETED',
    INITIALIZE_APP_FAILED = 'INITIALIZE_APP_FAILED',
    APP_CONFIG_RECEIVED = 'APP_CONFIG_RECEIVED',
    INITIALIZE_MODEL_COMPLETED = 'INITIALIZE_MODEL_COMPLETED',
    SET_RESULT = 'SET_RESULT',
    INITIALIZE_MODAL_COMPLETED = 'INITIALIZE_MODAL_COMPLETED',
    SET_MODAL_STATE = 'SET_MODAL_STATE',
    GO_TO_FORM_INFO = 'GO_TO_FORM_INFO',
    SET_VIEW_INFO_HEIGHT = 'SET_VIEW_INFO_HEIGHT',
    SET_VIEW_INFO_ERROR = 'SET_VIEW_INFO_ERROR',
    SAVE_PASSPORT_REQUESTED = 'SAVE_PASSPORT_REQUESTED',
    SAVE_PASSPORT_COMPLETED = 'SAVE_PASSPORT_COMPLETED',
    SAVE_PASSPORT_FAILED = 'SAVE_PASSPORT_FAILED',
    SAVE_INSURANCE_REQUESTED = 'SAVE_INSURANCE_REQUESTED',
    SAVE_INSURANCE_COMPLETED = 'SAVE_INSURANCE_COMPLETED',
    SAVE_INSURANCE_FAILED = 'SAVE_INSURANCE_FAILED'
}
